# Generated by Django 6.1.1 on 2026-10-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('language', models.CharField(help_text='ISO 639-1 code of the audio.', max_length=8)),
                ('subtitles', models.CharField(blank=True, help_text='ISO 639-1 code, empty for none.', max_length=8)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='halls.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='catalog.movie')),
            ],
            options={
                'ordering': ['starts_at', 'hall'],
            },
        ),
    ]
