# Generated by Django 6.1.1 on 2026-10-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('format', models.CharField(blank=True, help_text='For example IMAX or Dolby Atmos.', max_length=40)),
                ('rows', models.PositiveSmallIntegerField()),
                ('seats_per_row', models.PositiveSmallIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveSmallIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.hall')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='halls.seattype')),
            ],
            options={
                'ordering': ['hall', 'row', 'number'],
                'constraints': [models.UniqueConstraint(fields=('hall', 'row', 'number'), name='unique_seat_position')],
            },
        ),
    ]
