# Generated by Django 6.1.1 on 2026-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('now_showing', 'Now showing'), ('coming_soon', 'Coming soon'), ('archive', 'Archive')], db_index=True, default='coming_soon', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('trailer_youtube_id', models.CharField(blank=True, max_length=20)),
                ('poster_url', models.URLField(blank=True, help_text='Leave empty to use the generated demo poster.')),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('wikidata_id', models.CharField(blank=True, max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre')),
            ],
            options={
                'ordering': ['-popularity', 'title'],
            },
        ),
    ]
